---
apiVersion: batch/v1
kind: Job
metadata:
  name: flying-pigs-hazelcast-submit-job
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: flying-pigs-hazelcast-job
          image: harbor.codemowers.eu/msergo/flying-pigs-hazelcast@sha256:e76b7515e26a5b3f97fd4c513b36f3997ae22d1c55014309c6f0f4a20bded39e
          env:
            - name: ENVIRONMENT
              value: "prod"
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: USER_EMAIL
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: USER_PASSWORD
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: API_URL
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: RABBITMQ_PASSWORD

          command:
            [
                "sh",
                "-c",
                "jet -t hazelcast-jet-service submit /jobs/job.jar",
            ]
      restartPolicy: Never
  backoffLimit: 3
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 100
