---
apiVersion: batch/v1
kind: Job
metadata:
  name: flying-pigs-hazelcast-submit-job
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: flying-pigs-hazelcast-job
          image: harbor.codemowers.eu/msergo/flying-pigs-hazelcast@sha256:c2d520f5a0f319cd19b881d434228f28c107634f3984958a2f461a0f974a613d
          env:
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: USER_EMAIL
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: USER_PASSWORD
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: flying-pigs-hazelcast-secrets
                  key: API_URL

          command:
            [
              "sh",
              "-c",
              "jet -t hazelcast-jet-service submit /jobs/flying-pigs-hazelcast-1.0-SNAPSHOT-jar-with-dependencies.jar",
            ]
      restartPolicy: Never
  backoffLimit: 3
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 100
